# YAML Tips:
# Make sure paths are enclosed in single quotes
# IMPORTANT: write paths Unix-style with '/' NOT Windows-style with '\'
# Booleans are Yes or no


# Txt file containing PC names you want to create wallpapers for
# One PC name per line
TargetList: 'C:/Temp/testtargets.txt'


BasicPaths:

  ImageSourcePaths:
    CTS_RegularImagePath : '//doit-files/ATEC/CTS/CTS_Distribution/23_Summer/Background.jpg'
    ITSS_Labs_RegularImagePath : ''
    ITSS_RegularImagePath : ''

  # Local, non-UNC path that the altered image will be saved to.  (Set your GPO to this)
  # Note: if updating wallpaper, make sure you set this to a unique name, because Windows
  LocalDestination : 'C:/DesktopWallpaper23_24.jpg'  

  LogFileDirectory : 'C:/Temp/WallpaperLogs'

  AssetTagKey: 'REGISTRY::HKEY_LOCAL_MACHINE/SOFTWARE/Chico'
  AssetTag_REG_SZ: 'Chico_AssetTag'
  

Ownership :
  
  # Used for strict name matching
  DepartmentRegexPatterns : 
    '^SC-{1}[a-zA-Z]{3,4}\d{3,4}-{1}\d{1,2}' : 'CTS, SPECIAL'
    '^SC-{1}[a-zA-Z]{3,4}\d{3,4}' :            'CTS, Classroom'
    '^CONF-{1}[a-zA-Z]{3,4}\d{3,4}' :          'CTS, Conference'
    '^[a-zA-Z]{1}\d{5}-{1}.*$' :               'ITSS, Labs'
    '^[a-zA-Z]{1}\d{5}$' :                     'ITSS'   

  # Used for loose name matching
  DepartmentKeywords :
    'SC-*' : 'CTS'
    'CONF-*' : 'CTS'

  # used for Get-ADComputer matching
  DepartmentOU :
    'Classrooms' : 'CTS'
    'Conference' : 'CTS'
    'GLNN 104' : 'ITSS'

  # If we can't find a match to determine ownership, fallback to this group
  Fallback : 'ITSS'

  # 'Department' : 'Text that will be written below PC name and Asset Tag number'
  ContactStrings:
    'CTS' : 'Classroom Technology Services x5475'
    'ITSS' : 'IT Support Services x4357'


TextPosition:
  X: 1400
  Y: 1125