# YAML Tips:
# Make sure paths are enclosed in single quotes
# IMPORTANT: write paths Unix-style with '/' NOT Windows-style with '\'
# Booleans are Yes or no


# Txt file containing PC names you want to create wallpapers for
# One PC name per line
TargetList: 'C:/Temp/testtargets.txt'


BasicPaths:

  ImageSourcePaths:
    Department1 : '//my-server/Background.jpg'
    Department2 : '//their-server/Background.jpg'

  # Local, non-UNC path that the altered image will be saved to.  (Set your GPO to this)
  # Note: if updating wallpaper, make sure you set this to a unique name, because Windows
  LocalDestination : 'C:/DesktopWallpaper23_24.jpg'  

  LogFileDirectory : 'C:/Temp/WallpaperLogs'

  AssetTagKey: 'REGISTRY::HKEY_LOCAL_MACHINE/SOFTWARE/YourOrgIfYouHaveThis'
  AssetTag_REG_SZ: 'AssetTag'
  

Ownership :
  
  # Used for strict name matching
  DepartmentRegexPatterns : 
    '^SC-{1}[a-zA-Z]{3,4}\d{3,4}-{1}\d{1,2}' : 'Department1, SPECIAL'
    '^SC-{1}[a-zA-Z]{3,4}\d{3,4}' :            'Department1, Classroom'
    '^CONF-{1}[a-zA-Z]{3,4}\d{3,4}' :          'Department1, Conference'
    '^[a-zA-Z]{1}\d{5}-{1}.*$' :               'Department2, Labs'
    '^[a-zA-Z]{1}\d{5}$' :                     'Department2, Regular'   

  # Used for loose name matching
  DepartmentKeywords :
    'COMP-*' : 'Department1'
    'LAB-*' : 'Department2'

  # used for Get-ADComputer matching
  DepartmentOU :
    'Classrooms' : 'Department1'
    'ScienceLabs' : 'Department2'

  # If we can't find a match to determine ownership, fallback to this group
  Fallback : 'Department2'

  # 'Department' : 'Text that will be written below PC name and Asset Tag number'
  ContactStrings:
    'Department1' : 'Some Office 555-6666'
    'Department2' : 'Your Help Desk 555-5555'


TextPosition:
  X: 1400
  Y: 1125